import { useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";
import { useParams } from "react-router-dom";
import { CheckCircle2, ReceiptText, ShieldCheck, XCircle } from "lucide-react";
import { api, safeRequest } from "../services/api";
import { currency } from "../utils/formatters";
import { useDocumentTitle } from "../utils/useDocumentTitle";

const fallback = {
  verification: {
    valid: true,
    receiptId: "HHV-demo",
    verificationId: "HHV-demo",
    bookingId: "b1",
    status: "confirmed",
    paymentStatus: "paid",
    currency: "PKR",
    financialDetailsRedacted: true,
    issuedBy: "Basera Pakistan",
    issuedAt: "2026-06-03",
    property: "Cozy Boys Hostel F-10"
  },
  demo: true
};

export function ReceiptVerifyPage() {
  const { receiptId } = useParams();
  const [result, setResult] = useState(fallback);
  const [loading, setLoading] = useState(true);
  useDocumentTitle("Verify Receipt | Basera");

  useEffect(() => {
    safeRequest(() => api.get(`/documents/verify/${receiptId || "HHV-demo"}`), fallback).then((response) => {
      setResult(response);
      setLoading(false);
    });
  }, [receiptId]);

  const verification = result.verification || fallback.verification;
  const isValid = verification.valid !== false;
  const detailRows = [
    ["Receipt ID", verification.receiptId || receiptId],
    ["Verification ID", verification.verificationId],
    ["Booking", verification.bookingId],
    ["Property", verification.property],
    ["Booking Status", verification.status],
    ["Payment Status", verification.paymentStatus],
    ["Financial Details", verification.financialDetailsRedacted ? "Redacted on public verification" : currency(verification.amount || 0)],
    ["Issued By", verification.issuedBy]
  ];

  return (
    <>
      <Helmet>
        <title>Verify Receipt | Basera</title>
        <meta name="description" content="Verify a Basera receipt or booking document." />
      </Helmet>
      <main className="container-page py-12">
        <section className="mx-auto grid max-w-4xl gap-7 lg:grid-cols-[1fr_320px]">
          <div className="panel p-8 sm:p-10">
            <span className={`badge ${isValid ? "bg-accent-50 text-accent-700" : "bg-[#FEE2E2] text-[#991B1B]"}`}>
              {isValid ? <CheckCircle2 size={16} /> : <XCircle size={16} />}
              {isValid ? "Verified document" : "Not verified"}
            </span>
            <h1 className="mt-5 text-3xl font-extrabold sm:text-4xl">Receipt Verification</h1>
            <p className="mt-3 text-slate-700">
              This page confirms whether a Basera receipt ID exists in the platform record. It does not expose private tenant or Host contact details.
            </p>

            <div className="mt-8 grid gap-4 sm:grid-cols-2">
              {detailRows.map(([label, value]) => (
                <div key={label} className="rounded-lg border border-line bg-canvas p-4">
                  <p className="text-xs font-bold uppercase tracking-widest text-slate-600">{label}</p>
                  <p className="mt-2 font-semibold text-ink">{value || "-"}</p>
                </div>
              ))}
            </div>
          </div>

          <aside className="panel h-fit p-7">
            <span className="grid h-14 w-14 place-items-center rounded-lg bg-primary-50 text-primary-800">
              <ReceiptText />
            </span>
            <h2 className="mt-5 text-xl font-bold">Public Check</h2>
            <p className="mt-2 text-sm text-slate-700">
              Use this screen for receipts, rent ledgers, booking confirmations, and dispute resolution letters generated by Basera.
            </p>
            <div className="mt-6 rounded-lg bg-primary-50 p-4 text-sm text-primary-800">
              <ShieldCheck className="mb-2" size={20} />
              {loading ? "Checking receipt..." : result.demo ? "Demo verification mode is active." : "Live database verification completed."}
            </div>
          </aside>
        </section>
      </main>
    </>
  );
}
