const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");

const formatCurrency = (amount) => `PKR ${Number(amount || 0).toLocaleString("en-PK")}`;

const receiptIdFor = (prefix = "HH-RCT", id = "demo") => {
  const year = new Date().getFullYear();
  const cleaned = String(id || "demo").replace(/[^a-zA-Z0-9]/g, "").slice(-8) || "demo";
  return `${prefix}-${year}-${cleaned}`.toUpperCase();
};

const verificationUrlFor = (receiptId) => {
  const base = process.env.PUBLIC_APP_URL || process.env.CLIENT_URL || "http://localhost:5173";
  return `${base.replace(/\/$/, "")}/verify/${encodeURIComponent(receiptId)}`;
};

const buildQrBuffer = async (value) => {
  if (!value) return null;
  const dataUrl = await QRCode.toDataURL(value, { margin: 1, width: 160 });
  return Buffer.from(dataUrl.split(",")[1], "base64");
};

const drawBrandHeader = (doc, title, subtitle) => {
  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor("#0037b7")
    .text("Basera", 48, 34);

  doc
    .font("Helvetica-Bold")
    .fontSize(22)
    .fillColor("#0f172a")
    .text(title, 48, 76, { align: "center" });

  if (subtitle) {
    doc
      .font("Helvetica")
      .fontSize(11)
      .fillColor("#475569")
      .text(subtitle, 48, 104, { align: "center" });
  }

  doc.moveTo(48, 132).lineTo(564, 132).strokeColor("#d8dfef").stroke();
};

const drawRows = (doc, rows = []) => {
  let y = 154;
  rows.forEach(([label, value]) => {
    if (y > 700) {
      doc.addPage();
      y = 72;
    }
    doc.font("Helvetica-Bold").fontSize(10).fillColor("#334155").text(String(label), 48, y, { width: 190 });
    doc.font("Helvetica").fontSize(10).fillColor("#0f172a").text(String(value ?? "-"), 232, y, { width: 320 });
    y += 24;
  });
  return y;
};

const drawVerificationBlock = (doc, { receiptId, verificationUrl, qrBuffer }, startY) => {
  if (!receiptId) return startY;
  const y = Math.max(startY + 18, 590);
  doc.roundedRect(48, y, 516, 112, 8).fillAndStroke("#f4f7ff", "#d8dfef");
  doc.font("Helvetica-Bold").fontSize(11).fillColor("#0037b7").text("Public Verification", 68, y + 18);
  doc.font("Helvetica").fontSize(9).fillColor("#334155").text(`Receipt ID: ${receiptId}`, 68, y + 40, { width: 330 });
  doc.font("Helvetica").fontSize(9).fillColor("#334155").text(`Verify online: ${verificationUrl}`, 68, y + 58, { width: 330 });
  doc.font("Helvetica").fontSize(8).fillColor("#64748b").text("Scan the QR code or open the verification page to confirm this document was generated by Basera.", 68, y + 78, { width: 330 });
  if (qrBuffer) doc.image(qrBuffer, 468, y + 16, { width: 76, height: 76 });
  return y + 124;
};

const buildPdf = async ({ title, subtitle, rows = [], footer = "This is a computer-generated document and is valid without signature. Disputes: support@basera.pk", receiptId, verificationUrl }) => {
  const finalReceiptId = receiptId || null;
  const finalVerificationUrl = finalReceiptId ? verificationUrl || verificationUrlFor(finalReceiptId) : null;
  const qrBuffer = finalVerificationUrl ? await buildQrBuffer(finalVerificationUrl) : null;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "A4", info: { Title: title, Author: "Basera Pakistan" } });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    drawBrandHeader(doc, title, subtitle);
    const nextY = drawRows(doc, rows);
    const footerY = drawVerificationBlock(doc, { receiptId: finalReceiptId, verificationUrl: finalVerificationUrl, qrBuffer }, nextY);

    doc
      .fontSize(8)
      .fillColor("#64748b")
      .text(footer, 48, Math.min(footerY + 8, 760), { width: 516 });
    doc.end();
  });
};

const documentRows = (booking = {}) => [
  ["Booking ID", booking._id || booking.id],
  ["Status", booking.status],
  ["Payment Status", booking.paymentStatus],
  ["Rent", formatCurrency(booking.totalRent)],
  ["Security Deposit", formatCurrency(booking.securityDeposit)],
  ["Service Fee", formatCurrency(booking.serviceFee)],
  ["Commission", formatCurrency(booking.commission)],
  ["Host Payout", formatCurrency(booking.ownerReceives)]
];

module.exports = { buildPdf, documentRows, formatCurrency, receiptIdFor, verificationUrlFor };
