const PDFDocument = require("pdfkit");

const buildReceiptPdf = (booking) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(22).text("Basera Booking Receipt", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`Booking ID: ${booking._id || booking.id}`);
    doc.text(`Status: ${booking.status}`);
    doc.text(`Payment: ${booking.paymentMethod} - ${booking.paymentStatus}`);
    doc.text(`Total Amount: PKR ${booking.totalAmount}`);
    doc.text(`Commission: PKR ${booking.commission}`);
    doc.text(`Host Payout: PKR ${booking.ownerReceives}`);
    doc.moveDown();
    doc.text("This receipt was generated by Basera Pakistan.");
    doc.end();
  });

module.exports = { buildReceiptPdf };
